runtime: nodejs14
env: standard
instance_class: F1
service: buyerapp
env_variables:
  BUYER_APP_URL: "https://buyerapp-dot-test-sample-381704.el.r.appspot.com"
  GATEWAY_URL: "https://registry-dot-test-sample-381704.el.r.appspot.com"
  REGISTRY_URL: "https://registry-dot-test-sample-381704.el.r.appspot.com"
